// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VIAPadelClub.Infrastructure.EfcDomainPersistence;

#nullable disable

namespace VIAPadelClub.Infrastructure.EfcDomainPersistence.Migrations
{
    [DbContext(typeof(DomainModelContext))]
    partial class DomainModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");
#pragma warning restore 612, 618
        }
    }
}
